package lx

import "core:testing"
import "core:math"
import "core:fmt"

// NOTE :: Most of these test are generated by a model
// in a black box like setting

ctx := Context{}

@private
expect_approx :: proc(got: f32, expected: f32) {
    assert(math.abs(got - expected) <= 0.01, fmt.aprintf("expected %f, got %f", expected, got))
}

@(test)
test_box :: proc(t: ^testing.T) {
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)
    b := box("root", 1.0, 1.0)
    testing.expect_value(t, b.w, f32(1.0))
    testing.expect_value(t, b.h, f32(1.0))
    testing.expect_value(t, b.direction, Direction.Row)
    testing.expect_value(t, b.debug_label, "root")
}

@(test)
test_text :: proc(t: ^testing.T) {
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)
    txt := text("hello")
    testing.expect_value(t, txt.size, _Text_Size)
}

@(test)
test_add_elements :: proc(t: ^testing.T) {
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)
    root := box("root", 1.0, 1.0, .Col)
    child := box("child", 0.5, 0.5)
    txt := text("hello")
    add_elements(root, child, txt)

    assert(len(root.elements) == 2, "Expected root's elements to be 2")
    root_child := root.elements[0].(^Box)
    assert(root_child.id == child.id)
    assert(root_child.w == child.w)
    assert(root_child.h == child.h)

    _, ok := root.elements[1].(^Text)
    assert(ok, "Expected second element to be Text")
}

@(test)
test_layout_single_child :: proc(t: ^testing.T) {
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1)
    child := box("c", 0.5, 1)
    add_elements(root, child)
    layout(root, { 0, 0, 100, 100 }, &ctx)

    c := root.elements[0].(^Box)
    testing.expect_value(t, c.bounds.x, f32(5))
    testing.expect_value(t, c.bounds.y, f32(5))
    testing.expect_value(t, c.bounds.w, f32(45))
    testing.expect_value(t, c.bounds.h, f32(90))
}

@(test)
test_layout_two_children_row :: proc(t: ^testing.T) {
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1)
    a := box("a", 0.4, 1)
    b := box("b", 0.6, 1)
    add_elements(root, a, b)
    layout(root, { 0, 0, 200, 100 }, &ctx)

    ca := root.elements[0].(^Box)
    cb := root.elements[1].(^Box)
    expect_approx(ca.bounds.x, 5)
    expect_approx(ca.bounds.w, 76)
    expect_approx(cb.bounds.x, 81)
    expect_approx(cb.bounds.w, 114)
}

@(test)
test_layout_two_children_col :: proc(t: ^testing.T) {
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1, .Col)
    a := box("a", 1, 0.3)
    b := box("b", 1, 0.7)
    add_elements(root, a, b)
    layout(root, { 0, 0, 100, 200 }, &ctx)

    ca := root.elements[0].(^Box)
    cb := root.elements[1].(^Box)
    expect_approx(ca.bounds.y, 5)
    expect_approx(ca.bounds.h, 57)
    expect_approx(cb.bounds.y, 62)
    expect_approx(cb.bounds.h, 133)
}

@(test)
test_layout_gap :: proc(t: ^testing.T) {
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1, style = { gap = 10 })
    a := box("a", 0.5, 1)
    b := box("b", 0.5, 1)
    add_elements(root, a, b)
    layout(root, { 0, 0, 200, 100 }, &ctx)

    ca := root.elements[0].(^Box)
    cb := root.elements[1].(^Box)
    testing.expect_value(t, ca.bounds.w, f32(90))
    testing.expect_value(t, cb.bounds.x, f32(105))
    testing.expect_value(t, cb.bounds.w, f32(90))
}

@(test)
test_layout_padding :: proc(t: ^testing.T) {
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1, style = { padding = 20 })
    child := box("c", 1, 1)
    add_elements(root, child)
    layout(root, { 0, 0, 200, 100 }, &ctx)

    c := root.elements[0].(^Box)
    testing.expect_value(t, c.bounds.x, f32(20))
    testing.expect_value(t, c.bounds.y, f32(20))
    testing.expect_value(t, c.bounds.w, f32(160))
    testing.expect_value(t, c.bounds.h, f32(60))
}

@(test)
test_justify_center :: proc(t: ^testing.T) {
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1, style = { justify = .Center })
    child := box("c", 0.5, 1)
    add_elements(root, child)
    layout(root, { 0, 0, 100, 100 }, &ctx)

    c := root.elements[0].(^Box)
    testing.expect_value(t, c.bounds.x, f32(27.5))
    testing.expect_value(t, c.bounds.w, f32(45))
}

@(test)
test_justify_end :: proc(t: ^testing.T) {
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1, style = { justify = .End })
    child := box("c", 0.5, 1)
    add_elements(root, child)
    layout(root, { 0, 0, 100, 100 }, &ctx)

    c := root.elements[0].(^Box)
    testing.expect_value(t, c.bounds.x, f32(50))
}

@(test)
test_align_center :: proc(t: ^testing.T) {
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1, style = { align = .Center })
    child := box("c", 0.5, 0.5)
    add_elements(root, child)
    layout(root, { 0, 0, 100, 100 }, &ctx)

    c := root.elements[0].(^Box)
    testing.expect_value(t, c.bounds.y, f32(27.5))
}

@(test)
test_align_end :: proc(t: ^testing.T) {
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1, style = { align = .End })
    child := box("c", 0.5, 0.5)
    add_elements(root, child)
    layout(root, { 0, 0, 100, 100 }, &ctx)

    c := root.elements[0].(^Box)
    testing.expect_value(t, c.bounds.y, f32(50))
}

@(test)
test_grow_single :: proc(t: ^testing.T) {
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1)
    child := box("c", -1, 1)
    add_elements(root, child)
    layout(root, { 0, 0, 200, 100 }, &ctx)

    c := root.elements[0].(^Box)
    testing.expect_value(t, c.bounds.w, f32(190))
    testing.expect_value(t, c.bounds.h, f32(90))
}

@(test)
test_grow_with_fixed :: proc(t: ^testing.T) {
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1)
    fixed := box("f", 0.4, 1)
    grow  := box("g", -1, 1)
    add_elements(root, fixed, grow)
    layout(root, { 0, 0, 200, 100 }, &ctx)

    cf := root.elements[0].(^Box)
    cg := root.elements[1].(^Box)
    testing.expect_value(t, cf.bounds.w, f32(76))
    testing.expect_value(t, cg.bounds.w, f32(114))
    testing.expect_value(t, cg.bounds.x, f32(81))
}

@(test)
test_grow_two :: proc(t: ^testing.T) {
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1)
    a := box("a", -1, 1)
    b := box("b", -1, 1)
    add_elements(root, a, b)
    layout(root, { 0, 0, 200, 100 }, &ctx)

    ca := root.elements[0].(^Box)
    cb := root.elements[1].(^Box)
    testing.expect_value(t, ca.bounds.w, f32(95))
    testing.expect_value(t, cb.bounds.w, f32(95))
    testing.expect_value(t, cb.bounds.x, f32(100))
}

@(test)
test_grow_cross_axis :: proc(t: ^testing.T) {
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1)
    child := box("c", 0.5, -1)
    add_elements(root, child)
    layout(root, { 0, 0, 200, 100 }, &ctx)

    c := root.elements[0].(^Box)
    testing.expect_value(t, c.bounds.w, f32(95))
    testing.expect_value(t, c.bounds.h, f32(90))
}

@(test)
test_grow_middle :: proc(t: ^testing.T) {
    // [fixed 0.3 | grow | fixed 0.3] in 200px row
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1)
    a := box("a", 0.3, 1)
    mid := box("mid", -1, 1)
    b := box("b", 0.3, 1)
    add_elements(root, a, mid, b)
    layout(root, { 0, 0, 200, 100 }, &ctx)

    ca   := root.elements[0].(^Box)
    cmid := root.elements[1].(^Box)
    cb   := root.elements[2].(^Box)
    expect_approx(ca.bounds.x, 5)
    expect_approx(ca.bounds.w, 57)
    expect_approx(cmid.bounds.x, 62)
    expect_approx(cmid.bounds.w, 76)
    expect_approx(cb.bounds.x, 138)
    expect_approx(cb.bounds.w, 57)
}

@(test)
test_grow_two_with_fixed :: proc(t: ^testing.T) {
    // [grow | fixed 0.2 | grow] in 200px row
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1)
    a := box("a", -1, 1)
    mid := box("mid", 0.2, 1)
    b := box("b", -1, 1)
    add_elements(root, a, mid, b)
    layout(root, { 0, 0, 200, 100 }, &ctx)

    ca   := root.elements[0].(^Box)
    cmid := root.elements[1].(^Box)
    cb   := root.elements[2].(^Box)
    testing.expect_value(t, ca.bounds.w,   f32(76))
    testing.expect_value(t, cmid.bounds.x, f32(81))
    testing.expect_value(t, cmid.bounds.w, f32(38))
    testing.expect_value(t, cb.bounds.x,   f32(119))
    testing.expect_value(t, cb.bounds.w,   f32(76))
}

@(test)
test_grow_with_gap :: proc(t: ^testing.T) {
    // [fixed 0.2 | grow] with gap=10 in 200px row
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1, style = { gap = 10 })
    a := box("a", 0.2, 1)
    b := box("b", -1, 1)
    add_elements(root, a, b)
    layout(root, { 0, 0, 200, 100 }, &ctx)

    ca := root.elements[0].(^Box)
    cb := root.elements[1].(^Box)
    // available_w = 200 - 10(gap) = 190
    testing.expect_value(t, ca.bounds.w, f32(36))     // 0.2 * 190
    testing.expect_value(t, cb.bounds.x, f32(51))     // 38 + 10
    testing.expect_value(t, cb.bounds.w, f32(144))    // 190 - 38
}

@(test)
test_image :: proc(t: ^testing.T) {
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)
    img_texture : any = ---
    img := image("img", img_texture, 10.0, 10.0)

    root := box("r", 1, 1, style = { gap = 10 })
    add_elements(root, img)
    layout(root, { 0, 0, 100, 100 }, &ctx)

    testing.expect_value(t, img.pos[0], f32(5))
    testing.expect_value(t, img.pos[1], f32(5))
}

@(test)
test_fixed_size :: proc(t: ^testing.T) {
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1)
    child := box("c", 50, 30, size_mode = .Mixed)
    add_elements(root, child)
    layout(root, { 0, 0, 200, 200 }, &ctx)

    c := root.elements[0].(^Box)
    testing.expect_value(t, c.bounds.w, f32(50))
    testing.expect_value(t, c.bounds.h, f32(30))
}

@(test)
test_fixed_with_relative :: proc(t: ^testing.T) {
    // [fixed 50px | relative fill] in 200px row
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1)
    fixed := box("f", 50, 30, size_mode = .Mixed)
    grow  := box("g", -1, 1)
    add_elements(root, fixed, grow)
    layout(root, { 0, 0, 200, 100 }, &ctx)

    cf := root.elements[0].(^Box)
    cg := root.elements[1].(^Box)
    testing.expect_value(t, cf.bounds.w, f32(50))
    testing.expect_value(t, cf.bounds.h, f32(30))
    // grow gets remaining: 190(avail) - 50(fixed) = 140
    testing.expect_value(t, cg.bounds.w, f32(140))
    testing.expect_value(t, cg.bounds.h, f32(90))
}

@(test)
test_fixed_cross_fill :: proc(t: ^testing.T) {
    // fixed width, -1 height should fill cross axis
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1)
    child := box("c", 50, -1, size_mode = .Mixed)
    add_elements(root, child)
    layout(root, { 0, 0, 200, 100 }, &ctx)

    c := root.elements[0].(^Box)
    testing.expect_value(t, c.bounds.w, f32(50))
    testing.expect_value(t, c.bounds.h, f32(90))
}

@(test)
test_wrap_row :: proc(t: ^testing.T) {
    // 3 children each 0.4 wide in a 200px row → first two fit, third wraps
    context.allocator = context.temp_allocator
    defer free_all(context.temp_allocator)

    root := box("r", 1, 1, style = { wrap = true, gap = 10 })
    a := box("a", 0.4, 0.3)
    b := box("b", 0.4, 0.3)
    c := box("c", 0.4, 0.3)
    add_elements(root, a, b, c)
    layout(root, { 0, 0, 200, 200 }, &ctx)

    ca := root.elements[0].(^Box)
    cb := root.elements[1].(^Box)
    cc := root.elements[2].(^Box)

    // available_w = 200 - 10 padding = 190
    // each child width = 0.4 * 190 = 76
    // a at x=5, b at x=5+76+10=91, used=91+76=167 fits
    // c would be at 167+10=177, 177+76=253 > 195, so wraps
    testing.expect_value(t, ca.bounds.x, f32(5))
    testing.expect_value(t, ca.bounds.y, f32(5))
    testing.expect_value(t, cb.bounds.x, f32(91))
    testing.expect_value(t, cb.bounds.y, f32(5))
    // c wraps: x resets to 5, y = 5 + line_height(57) + gap(10) = 72
    testing.expect_value(t, cc.bounds.x, f32(5))
    testing.expect_value(t, cc.bounds.y, f32(72))
}
